### ISSUE TITLE
Not all codes are supported

### ISSUE THREAD

**Issue by Slider-Whistle** [algernon/ucode#1]
I was struggling for a while with Phi Φ (U+03A6) and thought I'd managed to type it at one point, but instead, what I had really entered was this weird pipe thing ¦ (U+00A6). I did some screwing around, and the program seems to only be successful on some weird, arbitrary characters. It's probably weird thing on my end, but if you could look into this and see whether there is actually any issue, I'd be grateful.
Also, the guide given in the README file doesn't represent the latest changes to ucode.c.

I'd like to say that I'm very, very thankful that you've been developing this program, even if it is kind of an input-stealing hackjob. I'd been looking for something like it for ages, but didn't find it until I saw your [comment on an issue for Xorg](https://gitlab.freedesktop.org/xorg/lib/libx11/issues/9). The link you gave to the program was dead, but somehow I still managed to find it just by looking up your name, so it worked out somehow.
The SCIM input method editor provides functional support for directly entering unicode character IDs, but it's dead and it seems like it'll never support qt.
IBus, the more recent and popular IM had support for it, but it was replaced with a graphical character finding window that's designed around emoji, and doesn't actually index all of the unicode characters.
So aside from this program, it seems like a good implementation for this kind of of functionality is basically totally absent from UNIX.

**Comment by algernon** [comment]
I'm not the original author of this code, I merely took the latest sources, and fixed an issue or two. Just enough to make it work well enough for the one case I needed it for. I do not plan to work on it further. The only reason it isn't archived is because I'm happy to apply pull requests, but that's all I'm capable of doing.

Marking this as wontfix due to the above.
